require("busted")

local statsd = require("statsd")

describe("statsd", function()
            describe("count", function()
                        it("registers a count metric for the bucket", function()
                              local s = spy.on(statsd, "register")
                              statsd.count("num_users", 99)
                              assert.spy(s).was.called_with("openresty.count.num_users", "99|c")
                                                                      end)
                              end)

            describe("incr", function()
                        it("makes a count of one for the bucket", function()
                              local s = spy.on(statsd, "count")
                              statsd.incr("start_session_success")
                              assert.spy(s).was.called_with("openresty.counter.start_session_success", "1|c")
                                                          end)
                             end)

            describe("time", function()
                        it("registers a time metric for the bucket", function()
                              local s = spy.on(statsd, "register")
                              statsd.time("start_session_duration", 100)
                              assert.spy(s).was.called_with("openresty.timer.start_session_duration", "100|ms")
                                                                     end)
                             end)

            describe("register", function()
                        it("appends a metric string terminated with a newline to the buffer", function()
                              statsd.flush()
                              statsd.register("openresty.timer.start_session_duration", "100|ms")
                              statsd.register("openresty.counter.start_session_success", 1)
                              assert.are.equal(statsd.buffer[1], "openresty.timer.start_session_duration:100|ms\n")
                              assert.are.equal(statsd.buffer[2], "openresty.counter.start_session_success:1\n")
                                                                                              end)

                                 end)

            describe("flush", function()
                        it("empties the buffer", function()
                          statsd.flush()
                              statsd.buffer[1] = "something"
                              statsd.flush()
                              assert.are.equal(#statsd.buffer, 0)
                                                 end)
                   end)
            end)

